<link href="/assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/css/gallery.css" />
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <li class="sub-menu">
                      <a href="javascript:;">
                          <i class="fa fa-laptop"></i>
                          <span>Categories</span>
                      </a>
                      <ul><!-- class="sub" -->
                          <?php foreach($this->data as $rows) : ?>
                          <li><a  href="#"><?php echo $rows['cat_desc'];?></a></li>
                          <?php endforeach;?>
                      </ul>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
<!--main content start-->
  <section id="main-content">
      <section class="wrapper">
        <!-- page start-->
        <section class="panel">
          <header class="panel-heading">
              Product Galley
          </header>
          <div class="panel-body">
              <ul class="grid cs-style-3">
                  <li>
                      <figure>
                          <img src="/images/gallery/4.JPG" alt="img04">
                          <figcaption>
                              <h3>Mindblowing</h3>
                              <span>lorem ipsume </span>
                              <a class="fancybox" rel="group" href="/images/gallery/4.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/1.JPG" alt="img01">
                          <figcaption>
                              <h3>CURREN New Fashion Men's</h3>
                              <span>Date Stainless Steel Military Sport Quartz Wrist Watch</span>
                              <a class="fancybox" rel="group" href="/images/gallery/1.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/2.JPG" alt="img02">
                          <figcaption>
                              <h3>Military LED Day</h3>
                              <span>Date Analog Army Steel Band Sport Quartz Mens Wrist Watch Black</span>
                              <a class="fancybox" rel="group" href="/images/gallery/2.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/5.JPG" alt="img05">
                          <figcaption>
                              <h3>Men Fashion Watches</h3>
                              <span>Stainless Steel Leather Band Quartz Analog Sport Wrist Watch</span>
                              <a class="fancybox" rel="group" href="/images/gallery/5.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/3.JPG" alt="img03">
                          <figcaption>
                              <h3>New Men's Analog Quartz</h3>
                              <span>Date Sport Army Black Leather Wrist Watch</span>
                              <a class="fancybox" rel="group" href="/images/gallery/3.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/6.JPG" alt="img06">
                          <figcaption>
                              <h3>New Women Handbag</h3>
                              <span>Shoulder Bags Tote Purse PU Leather Ladies Messenger Hobo Bag</span>
                              <a class="fancybox" rel="group" href="/images/gallery/6.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/1.JPG" alt="img01">
                          <figcaption>
                              <h3>Awesome</h3>
                              <span>At vero eos</span>
                              <a class="fancybox" rel="group" href="/images/gallery/1.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/2.JPG" alt="img02">
                          <figcaption>
                              <h3>Music</h3>
                              <span>atque corrupti </span>
                              <a class="fancybox" rel="group" href="/images/gallery/2.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/3.JPG" alt="img03">
                          <figcaption>
                              <h3>Kate Spade Women's</h3>
                              <span>Cobble Hill Small Ella Leather Cross-Body Tote</span>
                              <a class="fancybox" rel="group" href="/images/gallery/3.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/7.JPG" alt="img07">
                          <figcaption>
                              <h3>Cheers</h3>
                              <span>Vera Bradley Mandy Tote</span>
                              <a class="fancybox" rel="group" href="/images/gallery/6.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/8.JPG" alt="img08">
                          <figcaption>
                              <h3>Fashion Women Lady</h3>
                              <span>Leather Shoulder Handbag Messenger Crossbody Bag Tote Satchel</span>
                              <a class="fancybox" rel="group" href="/images/gallery/8.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/9.JPG" alt="img09">
                          <figcaption>
                              <h3>Fashion New Women</h3>
                              <span>Leather Handbags Shoulder Bags Hobo Tote Casual Satchel Purse</span>
                              <a class="fancybox" rel="group" href="/images/gallery/9.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/10.JPG" alt="img10">
                          <figcaption>
                              <h3>NEW Women Handbag</h3>
                              <span>Shoulder Bags Tote Purse PU Leather Ladies Messenger Hobo Bag</span>
                              <a class="fancybox" rel="group" href="/images/gallery/10.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/11.JPG" alt="img11">
                          <figcaption>
                              <h3>Fashion Women Lady</h3>
                              <span>Summer Handbag Shoulder Bags Tote Purse Messenger Hobo Bag</span>
                              <a class="fancybox" rel="group" href="/images/gallery/11.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
                  <li>
                      <figure>
                          <img src="/images/gallery/12.JPG" alt="img12">
                          <figcaption>
                              <h3>Fashion Women Lady</h3>
                              <span>PU Leather Tote Shoulder Handbag Satchel Messenger bag Purse</span>
                              <a class="fancybox" rel="group" href="/images/gallery/12.JPG">Take a look</a>
                          </figcaption>
                      </figure>
                  </li>
              </ul>
        
          </div>
        </section>
      </section>
  </section>
  <!--main content end-->
<!-- page end-->
  <script class="include" type="text/javascript" src="/js/jquery.dcjqaccordion.2.7.min.js"></script>
  <script src="/assets/fancybox/source/jquery.fancybox.js"></script>
  <script src="/js/modernizr.custom.js"></script>

  <script type="text/javascript">
      $(function() {
        //    fancybox
          jQuery(".fancybox").fancybox();
      });
  </script>