<div id="containertemplate">
    <div id="content">
        <h1 class="bold">Sorry !, This page access is denied</h1>
        <p class="table-caption">If you want to access this page please contact system administrator.</p>
    </div>
    <div><a href="/admin/index/index">Go to back</a></div>
</div>
<script type="text/javascript">
var count = 6;
 
function countDown(){
    var timer = document.getElementById("timer");
    if(count > 0){
        count--;
        timer.innerHTML = "This page will redirect in "+count+" seconds.";
        setTimeout("countDown()", 1000);
    }else{
        window.location.href = "/admin/index/index";
    }
}
</script>
 
<br/>
 
<span id="timer">
<script type="text/javascript">countDown();</script>
</span>

