<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<table id="mainTable" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Account User</th>
            <th>Login Time</th>
            <th>Logout Time</th>
            <th>Access IP</th>
            <th>Access Browser</th>
            <th>Access OS</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>

    <tbody>
        <?php foreach ($this->data as $rows) :?>
        <tr>
            <td align="center"><?php echo $rows['use_name']." ".$rows['use_lastname'];?></td>
            <td align="center"><?php echo $rows['login_time'];?></td>
            <td align="center"><?php echo $rows['logout_time'];?></td>
            <td align="center"><?php echo $rows['acc_ip'];?></td>
            <td align="center"><?php echo $rows['acc_browser'];?></td>
            <td align="center"><?php echo $rows['acc_os'];?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#mainTable').dataTable();

} );
</script>