<!-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css"> -->
              <!-- page start-->
              <section class="panel">
                  <header class="panel-heading">
                      Editable Table
                  </header>
                  <div class="panel-body">
                      <div class="adv-table editable-table ">
                          <div class="clearfix">
                              <div class="btn-group">
                                  <button id="editable-sample_new" class="btn green">
                                      Add New <i class="fa fa-plus"></i>
                                  </button>
                              </div>
                              <div class="btn-group pull-right">
                                  <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                                  </button>
                                  <ul class="dropdown-menu pull-right">
                                      <li><a href="#">Print</a></li>
                                      <li><a href="#">Save as PDF</a></li>
                                      <li><a href="#">Export to Excel</a></li>
                                  </ul>
                              </div>
                          </div>
                          <div class="space15"></div>
<table class="table table-striped table-hover table-bordered" id="editable-sample">
    <thead>
        <tr>
            <th>Group Id</th>
            <th>Group Code</th>
            <th>Group Name</th>
            <th>Lastupdate</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>

    <tbody>
        <?php foreach ($this->data as $rows) :?>
        <tr>
            <td align="center"><?php echo $rows['grp_id'];?></td>
            <td align="center"><?php echo $rows['grp_code'];?></td>
            <td align="center"><?php echo $rows['grp_name'];?></td>
            <td align="center"><?php echo $rows['lastupdate'];?></td>
            <td><a class="edit" href="javascript:;">Edit</a></td>
            <td><a class="delete" href="javascript:;">Delete</a></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
                      </div>
                  </div>
              </section>
              <!-- page end-->
<br/><br/>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
      <script type="text/javascript" src="/assets/data-tables/DT_bootstrap.js"></script>
      <!--script for this page only-->
      <script src="/js/editable-table.js"></script>

      <!-- END JAVASCRIPTS -->
      <script>
          jQuery(document).ready(function() {
              EditableTable.init();
          });
      </script>