<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="<?php echo $this->sysSetting['HT_charset'];?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $this->sysSetting['HT_meta_description'];?>">
    <meta name="author" content="<?php echo $this->sysSetting['HT_meta_author'];?>">
    <meta name="keyword" content="<?php echo $this->sysSetting['HT_meta_keywords'];?>">
    <link rel="shortcut icon" href="/img/favicon.png">
    <title><?php echo $this->sysSetting['HT_application_name'];?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-reset.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/style-responsive.css" rel="stylesheet" />
    <link type="text/css" rel="stylesheet" href="/vendors/jquery-news-ticker/jquery.news-ticker.css">
    <!-- <link href="/css/menu.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
    <script src="/js/jquery.js"></script>
    <style>
<!--
/* .news-update-box {
  float: left;
  padding: 9px 20px;
  line-height: 30px;
} */
-->
</style>
  </head>
    <body>
    <section id="container" >
      <!--header start-->
      <header><!-- class="header white-bg" -->
        <div class="navbar navbar-default"><!-- default -->
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">H.T. System</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/admin/portal/index">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Main Content <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">News</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Master List <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/category/index">Category list</a></li>
                        <li><a href="/admin/product/index">Product list</a></li>
                        <li><a href="/admin/product-images/index">Picture thumbnail</a></li>
                    </ul>
                </li>
                <li><a href="#configuration">Configuration</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">System Management <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="/admin/group-user/index">Group account</a></li>
                    <li><a href="/admin/account/index">Manage account</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">System Backend</li>
                    <li><a href="/admin/system-setting/index">System setting</a></li>
                    <li><a href="/admin/translate/index">System language</a></li>
                    <li><a href="/admin/system-access/index">System access</a></li>
                    <li><a href="/admin/system-log/index">System log</a></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li style="margin-top: 13px;">Hello <?php echo $this->profile->use_name." ".$this->profile->use_lastname; ?></li>
                <li>&nbsp;</li>
                <li>&nbsp;</li>
                <li>&nbsp;</li>
                <li style="margin-top: 13px;"><span style="cursor: pointer;" title="Log out" onclick="javascript:void(logout());"><b>Log Out</b></span></li>
              </ul>
              
              
              <ul class="nav pull-right top-menu">
                  <li class="dropdown language">
                      <a data-close-others="true" data-hover="dropdown" data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <img src="/images/flags/us.png" alt="">
                          <span class="username">US</span>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="#"><img src="/images/flags/es.png" alt=""> Spanish</a></li>
                          <li><a href="#"><img src="/images/flags/de.png" alt=""> German</a></li>
                          <li><a href="#"><img src="/images/flags/ru.png" alt=""> Russian</a></li>
                          <li><a href="#"><img src="/images/flags/fr.png" alt=""> French</a></li>
                      </ul>
                  </li>
              </ul>
              
            </div><!--/.nav-collapse -->
            <!-- <div class="news-update-box hidden-xs"><span class="text-uppercase mrm pull-left"> News : </span>
                <ul id="news-update" class="ticker list-unstyled">
                    <li>Welcome to μAdmin - Responsive Multi-Style Admin Template</li>
                    <li>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.</li>
                </ul>
            </div> -->
          </div>
        </div>
      </header>
    <!--header end-->
    <?php echo $this->layout()->content; ?>
    <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              <?php echo sprintf($this->sysSetting['HT_footer_notes'], date("Y"));?>
          </div>
      </footer>
    <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/js/bootstrap.min.js"></script>
<!--     <script src="/vendors/jquery-news-ticker/jquery.news-ticker.js"></script> -->
<!--     <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> -->
  <script type="text/javascript">
    function logout() {
        if(confirm("Are you sure to logout from this system ?")) {
            window.location.href = '/admin/index/logout';
        }
    }
    //BEGIN JQUERY NEWS UPDATE
//     $('#news-update').ticker({
//         controls: false,
//         titleText: ''
//     });
  </script>
  </body>
</html>