<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $this->sysSetting['HT_meta_description'];?>">
    <meta name="author" content="<?php echo $this->sysSetting['HT_meta_author'];?>">
    <meta name="keyword" content="<?php echo $this->sysSetting['HT_meta_keywords'];?>">
    <link rel="shortcut icon" href="/img/favicon.png">
    <title><?php echo $this->sysSetting['HT_application_name'];?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-reset.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/style-responsive.css" rel="stylesheet" />
    <!-- <link href="/css/menu.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
    <script src="/js/jquery.js"></script>
  </head>
    <body>
    <section id="container" >
      <!--header start-->
      <header><!-- class="header white-bg" -->
        <div class="navbar navbar-default"><!-- default -->
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">H.T. System</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
          </div>
        </div>
      </header>
    <!--header end-->
    <?php echo $this->layout()->content; ?>
    <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              <?php echo sprintf($this->sysSetting['HT_footer_notes'], date("Y"));?>
              <a href="#" class="go-top">
                  <i class="icon-angle-up"></i>
              </a>
          </div>
      </footer>
    <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/js/bootstrap.min.js"></script>
  </body>
</html>