<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<table id="mainTable" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Category Description</th>
            <th>Product Active</th>
            <th>Status</th>
            <th>Lastupdate</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->data as $rows) :?>
        <tr>
            <td align="center"><?php echo $rows['cat_name'];?></td>
            <td align="center"><?php echo $rows['cat_desc'];?></td>
            <td align="center"><?php echo $rows['count'];?></td>
            <td align="center"><?php echo $rows['cat_status'];?></td>
            <td align="center"><?php echo $rows['lastupdate'];?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
    
    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
</table>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#mainTable').dataTable();

} );
</script>