<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<table id="mainTable" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>User Id</th>
            <th>Priority</th>
            <th>Name</th>
            <th>Message</th>
            <th>Datetime</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>

    <tbody>
        <?php foreach ($this->data as $rows) :?>
        <tr>
            <td align="center"><?php echo $rows['user_id'];?></td>
            <td align="center"><?php echo $rows['priority'];?></td>
            <td align="center"><?php echo $rows['name'];?></td>
            <td align="center"><?php echo $rows['message'];?></td>
            <td align="center"><?php echo $rows['timestamp'];?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<br/><br/>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#mainTable').dataTable();

} );
</script>