<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<table id="mainTable" class="display" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Category</th>
            <th>Name</th>
            <th>Description</th>
            <th>Image</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Status</th>
            <th>Createtime</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->data as $rows) :?>
        <tr>
            <td align="center"><?php echo $rows['cat_desc'];?></td>
            <td align="center"><?php echo $rows['pro_name'];?></td>
            <td align="center"><?php echo $rows['pro_desc'];?></td>
            <td align="center">
                <img height="150" alt="<?php echo $rows['pro_desc'];?>" src="<?php echo $rows['pro_img'];?>">
            </td>
            <td align="center"><?php echo $rows['pro_unit'];?></td>
            <td align="center"><?php echo number_format($rows['pro_price'], 2);?></td>
            <td align="center"><?php echo $rows['pro_status'];?></td>
            <td align="center"><?php echo $rows['pro_createtime'];?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
    
    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
</table>
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#mainTable').dataTable({
        "language": {
            "decimal": ",",
            "thousands": "."
        }
    });

} );
</script>